[workspace]
members = [
    "lmbr",
    "lmbr_build",
    "lmbr_editor",
    "lmbr_logger",
    "lmbr_sys",
    "editor_plugin",
]
default-members = [
    "lmbr",
    "lmbr_editor",
    "lmbr_logger",
    "lmbr_sys",
]
