[workspace]
members = [
    "lmbr",
    "lmbr_build",
    "lmbr_logger",
    "lmbr_sys",
    "editor_plugin",
    "asset_builder_plugin",
]
default-members = [
    "lmbr",
    "lmbr_logger",
    "lmbr_sys",
]
